# - name: DNS
#   port_mappings:
#     - tcp/53
#   parent_type: virtualization.virtualmachine
#   parent_name: virtual machine 1
# - name: DNS
#   port_mappings:
#     - udp/53
#   parent_type: virtualization.virtualmachine
#   parent_name: virtual machine 1
# - name: MISC
#   port_mappings:
#     - udp/4000
#   parent_type: dcim.device
#   parent_name: server01
