---
name: 🐛 Bug Report
description: Report a reproducible bug
labels: ["bug"]
body:
  - type: input
    attributes:
      label: NetBox version
      description: What version of NetBox are you currently running?
      placeholder: v3.x.x
    validations:
      required: true
  - type: input
    attributes:
      label: NetBox initializers version
      description: What version of NetBox initializers are you currently running?
      placeholder: v3.x.x
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed Behavior
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Example YAML
      description: Provide an example for the YAML file that is causing your issue
      placeholder: |
        ---
      render: YAML
    validations:
      required: true

