---
name: Linting

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code base
    steps:
      - id: git-checkout
        name: Checkout
        uses: actions/checkout@v7

      - name: Run Ruff check
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "check"

      - name: Run Ruff format check
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "format --check"

      - name: Run yamllint
        run: yamllint -c .yamllint.yaml .

